// Generated by https://quicktype.io

export interface Overview {
  id: string;
  network: string;
  user: string;
  audienceType: string;
  audience: number;
  today: number;
  isUp: boolean;
}

export interface OverviewToday {
  id: string;
  network: string;
  statsType: string;
  stats: number;
  porcentage: number;
  isUp: boolean;
}
